eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server.openshift.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8764
spring:
  application:
    name: service-ribbon.openshift.svc.cluster.local